name:                drawing-guessing-server
version:             0.1.0.0
category:            Web
dependencies:
- base >= 4.7 && < 5

executables:
  dg:
    main: Main.hs
    source-dirs: src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N -I0
