name:                drawing-guessing-server
version:             0.1.0.0
category:            Web

executables:
  dg:
    main: Main.hs
    source-dirs: src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N -I0
    dependencies:
      - base
      - bytestring
      - containers
      - http-types
      - mime-types
      - random
      - stm
      - text
      - wai
      - wai-extra
      - wai-websockets
      - warp
      - websockets
