name:                drawing-guessing-server
version:             0.1.0.0
category:            Web

library:
  source-dirs: src-shared
  dependencies:
    - aeson
    - base
    - containers
    - text
    - vector
    - websockets

executables:
  dg-server:
    main: Main.hs
    source-dirs: src
    ghc-options: -threaded -rtsopts "-with-rtsopts=-N -I0"
    dependencies:
      - async
      - base
      - bytestring
      - containers
      - drawing-guessing-server
      - http-types
      - mime-types
      - mwc-random
      - stm
      - text
      - vector
      - wai
      - wai-extra
      - wai-websockets
      - warp
      - websockets

  dg-client:
    main: Main.hs
    source-dirs: src-testclient
    ghc-options: -threaded -rtsopts "-with-rtsopts=-N -I0"
    dependencies:
      - async
      - base
      - bytestring
      - containers
      - drawing-guessing-server
      - http-types
      - mime-types
      - network-uri
      - text
      - vector
      - websockets
